name: Create branch

on:
  workflow_dispatch:
    manual-run:
      default: 'true'
      description: Create branch
      required: true
    inputs:
      releasebranch:
        required: true
        type: string  


jobs:
  create-release-branch-test:
    runs-on: ubuntu-latest
    steps:
    - name: Print inputs
      run: echo "${{ inputs.releasebranch }}"
    - name: Checkout
      uses: actions/checkout@v3
      with:
       repository: garimah/test
       ref: main
    - name: Pull
      run: git pull
    - name: Create branch
      run: git checkout -b "releases/sprint${{ inputs.releasebranch }}"
    - name: Push branch
      run: git push -u origin "releases/sprint${{ inputs.releasebranch }}"
  
  update-version:
    needs: create-release-branch-test
    env: 
     NEXT_VERSION: ${{ inputs.releasebranch }}
    runs-on: ubuntu-latest
    steps:
    - name: Print inputs
      run:  echo "${{ inputs.releasebranch }}"
    - name: Checkout
      uses: actions/checkout@v3
      with:
       repository: garimah/test
       ref: main
    - name: Pull
      run: git pull
    - name: update version
      run: 
          |
          nextversion=`expr ${{ inputs.releasebranch }} + 1`
          echo $nextversion
          mvn versions:set -DnewVersion=3.'$nextversion'.0-SNAPSHOT --file test1/pom.xml
          echo "$nextversion" > 'version'
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add test1/pom.xml
          git add version
          git commit -m "prepare for next dev cycle [[skip ci]"
          git push -u origin main 
    
  
   
