name: Create branch

on:
  workflow_dispatch:
    manual-run:
      default: 'true'
      description: Create branch
      required: true
    inputs:
      releasebranch:
        required: true
        type: string  


jobs:
  create-release-branch-test:
    
    runs-on: ubuntu-latest
    steps:
    - name: Print inputs
      run: echo "${{ inputs.releasebranch }}"
    - name: Checkout
      uses: actions/checkout@v3
      with:
       repository: garimah/test
       ref: main
    - name: Pull
      run: git pull
    - name: Create branch
      run: git checkout -b "${{ inputs.releasebranch }}"
    - name: Push branch
      run: git push -u origin "${{ inputs.releasebranch }}"
  
  update-version:
    needs: create-release-branch-test
    runs-on: ubuntu-latest

    steps:
    - name: Print inputs
      run:  echo "${{ inputs.releasebranch }}"
    - name: Checkout
      uses: actions/checkout@v3
      with:
       repository: garimah/test
       ref: main
    - name: Pull
      run: git pull
    - name: update version
      run: 
          |
          mvn versions:set -DnewVersion=3.'${{ vars.SPRINT }}'.0-SNAPSHOT --file test1/pom.xml
          echo "${{ inputs.releasebranch }}" > 'version'
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add test1/pom.xml
          git add version
          git commit -m "prepare for next dev cycle"
          git push -u origin main 
    
  
   
