# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    manual-run:
      default: 'true'
      description: Run scan manually
      required: true
  push:
    branches:
      - main
      - 'releases/**' 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env: 
      SPRINT_TAG: ''
    steps:
      - name: Print Branch name
        run: |
          echo ${{ github.ref }} and ${{ github.event_name }} 
      - name: Print sprinttag
        run: echo "${{ env.SPRINT_TAG }}"
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}
      - name: workflowdispatch
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/garimah/rnd/actions/workflows/maven-publish.yml/dispatches \
          -d '{"ref":"${{ env.BRANCH }}","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
        env:
          BRANCH: master
         
#       - name: Actual build
#         run: |
#            cat version
#            value=`cat version`
#            echo "SPRINT_TAG=sprint$value" >> $GITHUB_ENV
#            curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.PAT }}"\
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/garimah/rnd/dispatches \
#             -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}' 
        
     

