# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    manual-run:
      default: 'true'
      description: Run scan manually
      required: true
  push:
    branches:
      - main
      - 'releases/sprint**'   

jobs:
  build:
    if: ${{ github.ref == 'releases/sprint${{ vars.SPRINT }}' }} || ${{ github.ref == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env: 
      SPRINT_TAG: sprint 

   
    steps:
    - name: Calculate sprint tag
      shell: bash
      run: |
            echo "${{ github.ref }}"
            if ${{ github.ref == '*releases/sprint67*' }}; then 
             echo "${{ github.ref }}"
             echo "SPRINT_TAG=sprint${{ vars.SPRINT }}" >> $GITHUB_ENV
            elif ${{ github.ref  == 'refs/heads/main' }}; then
             echo "${{ github.ref  }}"
             echo "SPRINT_TAG=sprint${{ vars.NEXT_SPRINT }}" >> $GITHUB_ENV 
            else 
              echo "${{ github.ref  }}"
            fi   
    - name: Print sprinttag
      run: echo "${{ env.SPRINT_TAG }}"
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

#     - name: Build with Maven
#       run: |
#         echo ${{ vars.SPRINT }}
#         mvn -B package --file test1/pom.xml

#     - name: Publish to GitHub Packages Apache Maven
#       run: mvn deploy --file test1/pom.xml -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
