# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    manual-run:
      default: 'true'
      description: Run scan manually
      required: true
  push:
    branches:
      - main
      - 'releases/**' 
      - master 

    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env: 
      SPRINT_TAG: ''
    outputs:
      SPRINT_TAG: ${{ steps.setcommitlog.outputs.SPRINT_TAG }}  
      commitlog:  ${{ steps.setcommitlog.outputs.commitlog }}  
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Print Branch name
        run: |
          echo ${{ github.ref }} and ${{ github.event_name }}
      - name: Print commit details
        run: |
          value=`cat version`
          message=`${${{ github.event.head_commit.message }}//$'\n'/}`
          commitlog=`echo [${{ github.event.commits[0].timestamp }}] $message [${{ github.event.commits[0].author.username }}] [${{ github.event.commits[0].url }}]`
          echo "commitlog=$commitlog"

      - name: Print sprinttag
        run: echo "${{ env.SPRINT_TAG }}"
      - id: setcommitlog
        run: |
          cat version
          value=`cat version`
          echo "SPRINT_TAG=sprint$value" >> $GITHUB_ENV
          echo "SPRINT_TAG=sprint$value" >> $GITHUB_OUTPUT
          message=`${${{ github.event.head_commit.message }}//$'\n'/}`
          # message=$(sed -nE '1 s/# *(.*)/\1/p' <<< ${{ github.event.head_commit.message }})
          commitlog=`echo [${{ github.event.commits[0].timestamp }}] $message [${{ github.event.commits[0].author.username }}] [${{ github.event.commits[0].url }}]`
          echo "commitlog=$commitlog" >> $GITHUB_OUTPUT
  
         
  pushcommitlog:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: send commitlog
        run: |
           curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/garimah/rnd/dispatches \
            -d '{"event_type":"pushcommitlog","client_payload":{"ref": "${{env.REF}}", "commitlog": "${{ needs.build.outputs.commitlog }}", "sprint": "${{ needs.build.outputs.SPRINT_TAG }}" }}' 
        env: 
          REF: ${{ github.ref }}

                  
# Does not work          
#       - name: workflowdispatch
#         run: |
#           curl -L \
#           -X POST \
#           -H "Accept: application/vnd.github+json" \
#           -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}"\
#           -H "X-GitHub-Api-Version: 2022-11-28" \
#           https://api.github.com/repos/garimah/rnd/actions/workflows/maven-publish.yml/dispatches \
#           -d '{"ref":"${{ env.BRANCH }}","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
#         env:
#           BRANCH: master
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        
        
     

