# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    manual-run:
      default: 'true'
      description: Run scan manually
      required: true
  push:
    branches:
      - main
      - 'releases/**'   

jobs:
  build:
    if: ${{ github.ref == 'releases/sprint${{ vars.SPRINT }}' }} || ${{ github.ref == 'main' }} || ${{ github.ref == 'master'  }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env: 
      SPRINT_TAG: sprint
    steps:
      - name: Print Branch name
        run: echo ${{ github.ref }} and ${{ github.event_name }}
      
      - name: Check if release branch
        if: ${{ github.ref == 'refs/heads/releases/sprint67' }}
        run: echo "SPRINT_TAG=sprint${{ vars.SPRINT }}" >> $GITHUB_ENV
        
      - name: Check if main
        if: ${{ github.ref == 'master' || github.ref == 'main'}}
        run: echo "SPRINT_TAG=sprint${{ vars.NEXT_SPRINT }}" >> $GITHUB_ENV   
      
      - name: Print sprinttag
        run: echo "${{ env.SPRINT_TAG }}"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file


